const productos = [
    {
        id: 1,
        nombre: 'KRYDEX Tactical MED1 Medical Pouch',
        precio: 60,
        img:'../img/med-pouch/med-pouch-uno.PNG',
        cantidad : 1,
    },
    {
        id: 2,
        nombre: 'Krydex Tactical 9MM Pistol Magazine <br/> Pouch Double Stack',
        precio: 40,
        img:'../img/pouch-pistola/pouch-pistola-uno.PNG',
        cantidad : 1,
    },
    {
        id: 3,
        nombre: 'Krydex Tactical MOLLE Belt Low <br/> Profile Battle Cobra Belt',
        precio: 200,
        img:'../img/cinto-dos/cinto-home.PNG',
        cantidad : 1,
    },
    {
        id: 4,
        nombre: 'KRYDEX MK3 MK4 Micro Fight <br/> Chassis Modular Chest Rig',
        precio: 160,
        img:'../img/chest-mk4/chest-rig-uno.PNG',
        cantidad : 1,
    },
    {
        id: 5,
        nombre: 'KRYDEX FCPC V5 Carrier',
        precio: 480,
        img:'../img/fpc5/chaleco-home.PNG',
        cantidad : 1,
    },
    {
        id: 6,
        nombre: 'The Bison Belt™ de Ferro Concepts',
        precio: 430,
        img:'../img/cinto/cinto-home.PNG',
        cantidad : 1,
    },
    {
        id: 7,
        nombre: 'KRYDEX Elastic QUAD SMG<br/> Submachine Gun',
        precio: 25,
        img:'../img/pouch-cierre/pouch-cierre.PNG',
        cantidad : 1,
    },
    {
        id: 8,
        nombre: 'KRYDEX Zipper Insert Pocket',
        precio: 25,
        img:'../img/pouch-cierre/pouch-verde.PNG',
        cantidad : 1,
    },
    {
        id: 9,
        nombre: 'KRYDEX 7.62 Double Magazine<br/> Insert Pouch',
        precio: 25,
        img:'../img/doble-mag-inserto/doble-mag-uno.PNG',
        cantidad : 1,
    },
    {
        id: 10,
        nombre: 'KRYDEX Tactical Mini Dangler <br/> Drop Dump Pouch',
        precio: 35,
        img:'../img/dangler/dangler-uno.PNG',
        cantidad : 1,
    },
    {
        id: 11,
        nombre: 'KRYDEX Tactical D3CR Chest Rig',
        precio: 110,
        img:'../img/chest-rig-uno/chest-home.PNG',
        cantidad : 1,
    },
    {
        id: 12,
        nombre: 'KRYDEX Slim Plate Carrier',
        precio: 125,
        img:'../img/plate-carrier-slim/plate-carrier.PNG',
        cantidad : 1,
    },
];